### ISSUE TITLE
Ajout d'ID

### ISSUE THREAD

**Issue by EdouardBoute** [CERES-Sorbonne/EuroParser#9]
Hi²,

Ca serait chouette dans l'export d'avoir des ID ajoutés.

Quand je travaille avec Rainette je remouline l'export dans un script pour les rajouter (*Id_1, *Id_2...)
Pour TXM, ça permettrait de parcourir article par article également.

Merci ! 

EB

**Comment by Marceau-h** [comment]
Résolu dans la [v0.1.15](https://github.com/CERES-Sorbonne/EuroParser/releases/tag/v0.1.15)
